//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductFetcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMetric
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> NumOfRecords { get; set; }
        public Nullable<long> NumOfNewRecords { get; set; }
    }
}
