//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductData
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_en
    {
        public string ProductHash { get; set; }
        public string CouponImage { get; set; }
        public string Category { get; set; }
        public string ProductImage { get; set; }
        public string ProductSKU { get; set; }
        public string ProductURL { get; set; }
        public string CouponDetail { get; set; }
        public Nullable<System.DateTime> CouponStartDate { get; set; }
        public Nullable<System.DateTime> CouponEndDate { get; set; }
        public Nullable<float> OriginalPrice { get; set; }
        public Nullable<float> SalePrice { get; set; }
        public string ProductDescription { get; set; }
        public string ProductName { get; set; }
        public string SaleCity { get; set; }
        public string Store { get; set; }
        public string StoreChain { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
