//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductData
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public long id { get; set; }
        public string StoreName { get; set; }
        public string Category { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string ProductUrl { get; set; }
        public string Zipcode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string StoreChain { get; set; }
        public string HashKey { get; set; }
    }
}
